### PR TITLE
🤯 Migrate datetime+time to a minutes addition expression

### PR DESCRIPTION
**Pull request by rowanseymour**
I was secretly hoping nobody really does this because the migrated expression is a bit nuts.. but apparently it is a thing people do, or at least our existing docs say it's a thing you can do.

### CODE REVIEW

**Comment by nicpottier** [comment]
Wait but aren't people depending on the replacement behavior now? (we added that unit test for a reason no?)

**Comment by rowanseymour** [comment]
Replacement is still happening when the lefthand side is just a date - this matches legacy behavior and the exampples in our docs.

**Comment by nicpottier** [comment]
Oh for the love of god I can't wait to switch the editor, that is 🍌

**Comment by rowanseymour** [comment]
Yeah I honestly considered just telling this user I'm really sorry but can you just wait a month 😭

**Pull request merged**
