### PR TITLE
Add support for + in email

### PR DESCRIPTION
**Pull request by tybritten**
fixes https://github.com/nyaruka/goflow/issues/811

### CODE REVIEW

**Comment by rowanseymour** [comment]
@tybritten thanks tho I'm guessing you guys want this patched in your current mailroom so I've actually made this as a backported fix in https://github.com/nyaruka/goflow/releases/tag/v0.55.2-backport (and added a few more valid email chars)

**Comment by tybritten** [comment]
are you going to cut a v.5.2.6 of with the backport?

**Comment by rowanseymour** [comment]
@tybritten https://github.com/nyaruka/mailroom/releases/tag/v5.2.6

**Comment by tybritten** [comment]
Thanks!

**Comment by rowanseymour** [comment]
I should probably mention also that for now we're not accepting PRs on this repo, but we'll always try to be responsive to issues created.

**Comment by tybritten** [comment]
ok good to know. was just making the PR to expedite. Any other repos you don't want PR's on?

**Comment by rowanseymour** [comment]
Only applies to nyaruka/goflow and nyaruka/floweditor

**Pull request closed without merging**
